### ISSUE TITLE
인정 체크리스트

### ISSUE THREAD

**Issue by injeong-lee** [gitforyoung/iTshirt#7]
- [ ] 토마토

- [ ] 양상추

- [ ] 배추

**Comment by gitforyoung** [comment]
> * [v ]  토마토
> * [ ]  양상추
> * [ ]  배추

**Comment by gitforyoung** [comment]
- [ ] 토마토

- [ ] 양상추

- [ ] 배추

**Comment by gitforyoung** [comment]
- [ ] 토마토

- [ ] 양상추

- [ ] 배추

**Comment by injeong-lee** [comment]
> * [x]  토마토
> * [ ]  양상추
> * [x]  배추
